### PR TITLE
Adding a default value to journal for the past day

### PR DESCRIPTION
**Pull request by ssherar**

### CODE REVIEW

**Comment by borntyping** [comment]
We can do this with `default='yesterday'`, but I'm mostly worried about what a user would have to do to see all entries.

**Comment by ssherar** [comment]
This is why I shouldn't code after 16 hours on the road and running around London like a lunatic!

I can see that all entries being an issue - but what use case is that for? nobody can process that many commit messages in one go, especially from 2+ repos?

On that note - would it be better if `--all` was implemented, it would pipe it into `more` for better output?

**Comment by borntyping** [comment]
Yes, `--all` might be a better idea :)

Something like:
```python
if not any((all, since, until)):
    since = 'yesterday'
```

**Comment by ssherar** [comment]
:+1: on that. 

However, implementing `--all`, it appears that the gitpython implementation of commits returns nothing if there is a `None` value being passed in to the method parameters. Removing those arguments from the dictionary lists all commits in it's simple form.

**Comment by borntyping** [comment]
Huh, passing both as all Works For Me(tm). :/

**Comment by ssherar** [comment]
```shell
(tg)sambuca@Sams-MacBook-Pro  ~/Documents/projects/tg   git:feature/default-journal-date
 >>  tg journal
(None, None)
(tg)sambuca@Sams-MacBook-Pro  ~/Documents/projects/tg   git:feature/default-journal-date
 >>  tg journal --since 11/03/15
(u'11/03/15', None)
2015-03-12 11:05:34 b21d912 formulary  Removing debug print statements
2015-03-12 13:37:13 658eae3 formulary  Adding TableView for Website Links
```

**Pull request closed without merging**
